# Generated by Django 4.0.5 on 2022-08-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_createalbum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createalbum',
            name='description',
        ),
    ]
