# Generated by Django 4.0.5 on 2022-08-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_remove_createalbum_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createalbum',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
